package sqlite
import("context";"database/sql";"encoding/json";"errors";"fmt";"github.com/marellasunil/FleetAMP/internal/lifecycle";"github.com/marellasunil/FleetAMP/internal/storage")
type ComponentLifecycleExecutionStore struct{db *sql.DB}
func(s *ComponentLifecycleExecutionStore)Create(ctx context.Context,value *lifecycle.ExecutionPlan)error{targets,err:=json.Marshal(value.Targets);if err!=nil{return err};_,err=s.db.ExecContext(ctx,`INSERT INTO component_lifecycle_execution_plans(id,approval_id,request_id,request_spec_hash,validation_id,validation_hash,executor_kind,operation,component_type,deployment_method,targets,plan_hash,prepared_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,value.ID,value.ApprovalID,value.RequestID,value.RequestSpecHash,value.ValidationID,value.ValidationHash,value.ExecutorKind,value.Operation,value.ComponentType,value.DeploymentMethod,string(targets),value.PlanHash,value.PreparedBy,formatTime(value.CreatedAt));if err!=nil{return fmt.Errorf("create component lifecycle execution plan: %w",err)};return nil}
func(s *ComponentLifecycleExecutionStore)Get(ctx context.Context,id string)(*lifecycle.ExecutionPlan,error){value,err:=scanLifecycleExecution(s.db.QueryRowContext(ctx,lifecycleExecutionSelect+` WHERE id=?`,id));if errors.Is(err,sql.ErrNoRows){return nil,storage.ErrComponentLifecycleExecutionNotFound};return value,err}
func(s *ComponentLifecycleExecutionStore)List(ctx context.Context,limit int)([]*lifecycle.ExecutionPlan,error){if limit<=0||limit>500{limit=100};rows,err:=s.db.QueryContext(ctx,lifecycleExecutionSelect+` ORDER BY created_at DESC LIMIT ?`,limit);if err!=nil{return nil,err};defer rows.Close();result:=[]*lifecycle.ExecutionPlan{};for rows.Next(){value,err:=scanLifecycleExecution(rows);if err!=nil{return nil,err};result=append(result,value)};return result,rows.Err()}
const lifecycleExecutionSelect=`SELECT id,approval_id,request_id,request_spec_hash,validation_id,validation_hash,executor_kind,operation,component_type,deployment_method,targets,plan_hash,prepared_by,created_at FROM component_lifecycle_execution_plans`
type lifecycleExecutionScanner interface{Scan(...any)error}
func scanLifecycleExecution(scanner lifecycleExecutionScanner)(*lifecycle.ExecutionPlan,error){value:=&lifecycle.ExecutionPlan{};var kind,operation,targets,created string;if err:=scanner.Scan(&value.ID,&value.ApprovalID,&value.RequestID,&value.RequestSpecHash,&value.ValidationID,&value.ValidationHash,&kind,&operation,&value.ComponentType,&value.DeploymentMethod,&targets,&value.PlanHash,&value.PreparedBy,&created);err!=nil{return nil,err};value.ExecutorKind=lifecycle.ExecutorKind(kind);value.Operation=lifecycle.Operation(operation);if err:=json.Unmarshal([]byte(targets),&value.Targets);err!=nil{return nil,err};value.CreatedAt,_=parseTime(created);return value,nil}
var _ storage.ComponentLifecycleExecutionStore=(*ComponentLifecycleExecutionStore)(nil)
