package sqlite
import("context";"database/sql";"encoding/json";"fmt";"time";"github.com/marellasunil/FleetAMP/internal/guides")
type GuideCatalogStore struct{db *sql.DB}
func catalogJSON(c guides.Catalog)(string,error){b,e:=json.Marshal(c);return string(b),e};func parseCatalog(raw string)(guides.Catalog,error){var c guides.Catalog;e:=json.Unmarshal([]byte(raw),&c);return c,e}
func(s *GuideCatalogStore)seed(ctx context.Context)error{raw,e:=catalogJSON(guides.DefaultCatalog());if e!=nil{return e};if _,e=s.db.ExecContext(ctx,`INSERT OR IGNORE INTO guide_catalog_versions(version,content,created_by,created_at,published_at) VALUES(1,?,'system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,raw);e!=nil{return e};if _,e=s.db.ExecContext(ctx,`INSERT OR IGNORE INTO guide_catalog_state(singleton,active_version) VALUES(1,1)`);e!=nil{return e};_,e=s.db.ExecContext(ctx,`INSERT OR IGNORE INTO guide_catalog_draft(singleton,content,base_version,updated_by,updated_at) VALUES(1,?,1,'system',CURRENT_TIMESTAMP)`,raw);return e}
func(s *GuideCatalogStore)Draft(ctx context.Context)(guides.Catalog,error){if e:=s.seed(ctx);e!=nil{return guides.Catalog{},e};var raw string;if e:=s.db.QueryRowContext(ctx,`SELECT content FROM guide_catalog_draft WHERE singleton=1`).Scan(&raw);e!=nil{return guides.Catalog{},e};return parseCatalog(raw)}
func(s *GuideCatalogStore)SaveDraft(ctx context.Context,c guides.Catalog,actor string)error{if e:=c.Validate();e!=nil{return e};raw,e:=catalogJSON(c);if e!=nil{return e};_,e=s.db.ExecContext(ctx,`UPDATE guide_catalog_draft SET content=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE singleton=1`,raw,actor);return e}
func scanGuideVersion(row interface{Scan(...any)error})(guides.Version,error){var v guides.Version;var raw,created,published string;e:=row.Scan(&v.Version,&raw,&v.CreatedBy,&created,&published);if e!=nil{return v,e};v.Catalog,e=parseCatalog(raw);if e!=nil{return v,e};v.CreatedAt,_=time.Parse("2006-01-02 15:04:05",created);v.PublishedAt,_=time.Parse("2006-01-02 15:04:05",published);return v,nil}
func(s *GuideCatalogStore)Active(ctx context.Context)(guides.Version,error){if e:=s.seed(ctx);e!=nil{return guides.Version{},e};return scanGuideVersion(s.db.QueryRowContext(ctx,`SELECT v.version,v.content,v.created_by,v.created_at,v.published_at FROM guide_catalog_versions v JOIN guide_catalog_state s ON s.active_version=v.version WHERE s.singleton=1`))}
func(s *GuideCatalogStore)Publish(ctx context.Context,actor string)(guides.Version,error){c,e:=s.Draft(ctx);if e!=nil{return guides.Version{},e};if e=c.Validate();e!=nil{return guides.Version{},e};raw,_:=catalogJSON(c);tx,e:=s.db.BeginTx(ctx,nil);if e!=nil{return guides.Version{},e};defer tx.Rollback();var next int;if e=tx.QueryRowContext(ctx,`SELECT COALESCE(MAX(version),0)+1 FROM guide_catalog_versions`).Scan(&next);e!=nil{return guides.Version{},e};if _,e=tx.ExecContext(ctx,`INSERT INTO guide_catalog_versions(version,content,created_by,created_at,published_at) VALUES(?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,next,raw,actor);e!=nil{return guides.Version{},e};if _,e=tx.ExecContext(ctx,`UPDATE guide_catalog_state SET active_version=? WHERE singleton=1`,next);e!=nil{return guides.Version{},e};if _,e=tx.ExecContext(ctx,`UPDATE guide_catalog_draft SET base_version=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE singleton=1`,next,actor);e!=nil{return guides.Version{},e};if e=tx.Commit();e!=nil{return guides.Version{},e};return s.Active(ctx)}
func(s *GuideCatalogStore)Versions(ctx context.Context)([]guides.Version,error){if e:=s.seed(ctx);e!=nil{return nil,e};rows,e:=s.db.QueryContext(ctx,`SELECT version,content,created_by,created_at,published_at FROM guide_catalog_versions ORDER BY version DESC`);if e!=nil{return nil,e};defer rows.Close();var out []guides.Version;for rows.Next(){v,e:=scanGuideVersion(rows);if e!=nil{return nil,e};out=append(out,v)};return out,rows.Err()}
func(s *GuideCatalogStore)Rollback(ctx context.Context,version int,actor string)(guides.Version,error){var raw string;if e:=s.db.QueryRowContext(ctx,`SELECT content FROM guide_catalog_versions WHERE version=?`,version).Scan(&raw);e!=nil{return guides.Version{},fmt.Errorf("guide version %d not found",version)};c,e:=parseCatalog(raw);if e!=nil{return guides.Version{},e};if e=s.SaveDraft(ctx,c,actor);e!=nil{return guides.Version{},e};return s.Publish(ctx,actor)}
