server:
  endpoint: ws://127.0.0.1:14320/v1/opamp

capabilities:
  reports_effective_config: true
  reports_health: true
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: /otelcol-contrib

storage:
  directory: /var/lib/otel-supervisor
