apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-supervisor-storage
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
